SELECT POSTAGEM.CONTEUDO AS 'conteudo',
PESSOA.NOME AS 'Usuario',
COUNT(LIKES.ID) AS 'Likes',
(SELECT PESSOA.NOME FROM PESSOA WHERE ID = LIKES.ID_PESSOA) AS 'curtiu',
(SELECT PESSOA.NOME FROM PESSOA WHERE ID = COMENTARIO.ID_PESSOA) AS 'comentou',
(SELECT PESSOA.NOME FROM PESSOA WHERE ID = COMPARTILHAMENTO.ID_PESSOA) AS 'compartilhou'

FROM POSTAGEM AS POST
INNER JOIN PESSOA AS PES
ON POST.ID_PESSOA = PES.ID

INNER JOIN LIKE_POSTAGEM AS LIKES
ON LIKES.ID_POSTAGEM = POST.ID

INNER JOIN COMENTARIO AS COMENT
ON COMENT.ID_POSTAGEM = POST.ID

INNER JOIN COMPARTILHAMENTO AS COMP
ON COMP.ID_POSTAGEM = POST.ID;